export const PERFORMANCE_CATEGORIES = Object.freeze([
  Object.freeze({ id: "preparation", label: "Preparação da execução" }),
  Object.freeze({ id: "simulation", label: "Simulação e ticks" }),
  Object.freeze({ id: "evolution", label: "Transição evolutiva" }),
  Object.freeze({ id: "interface", label: "Interface e snapshots" }),
  Object.freeze({ id: "rendering", label: "Desenho e câmera" }),
  Object.freeze({ id: "events", label: "Eventos e persistência" }),
  Object.freeze({ id: "diagnostics", label: "Sobrecarga do diagnóstico" }),
]);

const DEFINITIONS = [
  ["execution.build", "Construção da execução", "preparation", null],
  ["execution.config", "Leitura e validação da configuração", "preparation", "execution.build"],
  ["map.generate", "Geração do mapa", "preparation", "execution.build"],
  ["map.terrain-noise", "fBm do terreno", "preparation", "map.generate"],
  ["map.archipelago", "Layout do arquipélago e lagos", "preparation", "map.generate"],
  ["map.productivity", "Produtividade e distância da água", "preparation", "map.generate"],
  ["map.tiles-snapshot", "Tiles e snapshot do mapa", "preparation", "map.generate"],
  ["execution.generation-initialize", "Inicialização da geração 1", "preparation", "execution.build"],
  ["execution.food-initialize", "Comidas iniciais", "preparation", "execution.generation-initialize"],
  ["execution.population-initialize", "População inicial", "preparation", "execution.generation-initialize"],
  ["execution.spawn-points", "Posições iniciais", "preparation", "execution.population-initialize"],
  ["execution.networks", "Genomas, redes e seres", "preparation", "execution.population-initialize"],
  ["execution.initial-perception", "Percepção inicial", "preparation", "execution.population-initialize"],

  ["frame.draw", "Frame p5 completo", "rendering", null],
  ["frame.update", "Atualização antes do desenho", "interface", "frame.draw"],
  ["clock.advance", "Relógio e lote de ticks", "simulation", "frame.update"],
  ["simulation.tick", "Tick físico completo", "simulation", "clock.advance"],
  ["food.process-tick", "Calendário e spawn de comidas", "simulation", "simulation.tick"],
  ["population.process-tick", "Atualização da população", "simulation", "simulation.tick"],
  ["population.decision-sensors", "Sensores nos ticks de decisão", "simulation", "population.process-tick"],
  ["population.decision-neural", "Inferência neural", "simulation", "population.process-tick"],
  ["population.physics", "Física e custos", "simulation", "population.process-tick"],
  ["population.consumption-search", "Busca por comida", "simulation", "population.process-tick"],
  ["food.consume", "Resolução do consumo", "simulation", "population.process-tick"],
  ["food.consume-normalize", "Validação e agrupamento das solicitações", "simulation", "food.consume"],
  ["food.consume-allocate", "Distribuição da energia", "simulation", "food.consume"],
  ["food.depleted-cleanup", "Remoção de comidas esgotadas", "simulation", "food.consume"],
  ["food.relocation", "Realocação por inatividade", "simulation", "food.consume"],
  ["population.apply-grants", "Concessão de energia", "simulation", "population.process-tick"],
  ["population.survival", "Fome, cura, morte e fitness", "simulation", "population.process-tick"],
  ["population.visual-sensors", "Percepção visual final", "simulation", "population.process-tick"],
  ["simulation.summary", "Resumo e verificação de término", "simulation", "simulation.tick"],
  ["simulation.timeline", "Amostra da timeline", "simulation", "simulation.tick"],
  ["simulation.snapshot-build", "Construção do snapshot da simulação", "interface", null],
  ["population.snapshot-build", "Snapshot e resumo da população", "interface", null],
  ["food.snapshot-build", "Snapshot das comidas", "interface", null],

  ["evolution.transition", "Transição de geração", "evolution", "simulation.tick"],
  ["evolution.candidates", "Candidatos e ranking", "evolution", "evolution.transition"],
  ["evolution.elite-archive", "Arquivo global de elites", "evolution", "evolution.transition"],
  ["evolution.metrics", "Métricas evolutivas", "evolution", "evolution.transition"],
  ["evolution.reproduction", "Reprodução genética", "evolution", "evolution.transition"],
  ["evolution.parent-selection", "Torneios e seleção de pais", "evolution", "evolution.reproduction"],
  ["evolution.genome", "Crossover e mutação", "evolution", "evolution.reproduction"],
  ["evolution.next-systems", "Sistemas da próxima geração", "evolution", "evolution.transition"],
  ["evolution.next-food", "Comidas da próxima geração", "evolution", "evolution.next-systems"],
  ["evolution.next-population", "População da próxima geração", "evolution", "evolution.next-systems"],
  ["evolution.next-spawn-points", "Posições da próxima geração", "evolution", "evolution.next-population"],
  ["evolution.next-networks", "Redes da próxima geração", "evolution", "evolution.next-population"],
  ["evolution.next-perception", "Percepção inicial da próxima geração", "evolution", "evolution.next-population"],
  ["evolution.history-timeline", "Histórico e timeline inicial", "evolution", "evolution.transition"],

  ["ui.render-snapshot", "Apresentação do snapshot", "interface", null],
  ["ui.render-config", "Resumo da configuração", "interface", null],
  ["ui.metrics-hints", "Métricas e valores atuais/pendentes", "interface", "ui.render-snapshot"],
  ["ui.map-stats", "Resumo do mapa", "interface", "ui.render-snapshot"],
  ["ui.history-chart", "Histórico evolutivo", "interface", "ui.render-snapshot"],
  ["ui.chartjs-history-update", "Atualização Chart.js do histórico", "interface", "ui.history-chart"],
  ["ui.timeline-charts", "Gráficos da geração", "interface", "ui.render-snapshot"],
  ["ui.chartjs-timeline-update", "Atualização Chart.js das timelines", "interface", "ui.timeline-charts"],
  ["ui.inspector", "Inspetor de entidade", "interface", "ui.render-snapshot"],

  ["render.interaction", "Reconciliação de seleção", "rendering", "frame.draw"],
  ["render.map-cache", "Reconstrução da camada do mapa", "rendering", "frame.draw"],
  ["render.follow-camera", "Acompanhamento e câmera", "rendering", "frame.draw"],
  ["render.background-map", "Fundo e composição do mapa", "rendering", "frame.draw"],
  ["render.sensors", "Raios dos sensores", "rendering", "frame.draw"],
  ["render.foods", "Desenho das comidas", "rendering", "frame.draw"],
  ["render.beings", "Desenho dos seres", "rendering", "frame.draw"],

  ["events.runtime-config", "Configuração dinâmica", "events", null],
  ["events.config-validation", "Leitura e validação do formulário", "events", "events.runtime-config"],
  ["events.settings-save", "Persistência das preferências", "events", null],
  ["events.selection", "Seleção de entidade", "events", null],
  ["events.camera", "Operação de câmera", "events", null],
  ["diagnostics.refresh", "Atualização do painel", "diagnostics", null],
];

export const PERFORMANCE_STAGES = Object.freeze(DEFINITIONS.map(
  ([id, label, category, parentId]) => Object.freeze({ id, label, category, parentId }),
));

export const PERFORMANCE_STAGE_BY_ID = new Map(
  PERFORMANCE_STAGES.map((stage) => [stage.id, stage]),
);
